# docker-compose.yml

version: '3.8'

services:
  api:
    build: ./api
    command: uvicorn src.entrypoints.fastapi_app:app --host 0.0.0.0 --port 8081
    ports:
      - 8081:8081
    environment:
    # Choose credential_type and remove unnecessary variables
    ## Local
      - credential_type=local
      - jwt_secret=
      - jwt_algorithm=
      - jwt_token_expiration=
      - db_user=
      - db_password=
      - db_host=db
      - db_port=
      - db_name=
    ## KeyVault
      - credential_type=cloud
      - db_host=db
      - key_vault_url=
      - azure_secrets=["jwt-secret", "db-user", "db-password", "db-port", "db-name"]
      - AZURE_CLIENT_ID=
      - AZURE_TENANT_ID=
      - AZURE_CLIENT_SECRET=
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/prepare_data.sql:/docker-entrypoint-initdb.d/prepare_data.sql
    expose:
      - 127.0.0.1:5432
    environment:
    # If deploying PostgreSQL then fill up variables
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=

volumes:
  postgres_data: