# docker-compose.yml

version: '3.8'

services:
  api:
    build: ./api
    command: uvicorn src.entrypoints.fastapi_app:app --host 0.0.0.0
    ports:
      - 8008:8000
    environment:
      - jwt_secret=test
      - db_user=postgres
      - db_password=test1234
      - db_host=db
      - db_port=5432
      - db_name=postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/prepare_data.sql:/docker-entrypoint-initdb.d/prepare_data.sql
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=postgres

volumes:
  postgres_data: